const express = require('express')
const router = express.Router()

// controllers
const LoginController = require('../controllers/LoginController')
const AdminPageController = require('../controllers/adminPageController')
const TeacherPageController = require('../controllers/teacherPageController')
const StudentPageController = require('../controllers/StudentPageController')
const AdminCourseController = require('../controllers/AdminCourseController')
const AdminTeacherController = require('../controllers/AdminTeacherController')
const AdminGroupController = require('../controllers/AdminGroupController')
const AdminStudentController = require('../controllers/AdminStudentController')
const TeacherAddHomeworkController = require('../controllers/addHomeworkController')
const StudentUploadHomeworkController = require('../controllers/StudentHomeWorkController')

// middlewares
const verifyRole = require('../middlewares/verifyRole')
const verifyToken = require('../middlewares/verifyToken')
const verifyRoute = require('../middlewares/verifyRoute')

router
    .get('/', verifyRoute, LoginController.LOGIN)
    .get('/admin/Courses', verifyToken, AdminPageController.ADMIN)
    .get('/admin/Teachers', verifyToken, AdminPageController.ADMIN_TEACHER)
    .get('/admin/Groups', verifyToken, AdminPageController.ADMIN_GROUP)
    .get('/admin/Students', verifyToken, AdminPageController.ADMIN_STUDENT)
    .get('/teacher/Groups', verifyToken, TeacherPageController.TEACHER)
    .get('/teacher/Students', verifyToken, TeacherPageController.TEACHER_STUDENT)
    .get('/student', verifyToken, StudentPageController.STUDENT)
    .post('/login', verifyRole, LoginController.LOGIN_POST)
    .post('/admin/coursepost', AdminCourseController.POST_COURSE)
    .delete('/admin/coursedelete/:id', AdminCourseController.DELETE_COURSE)
    .put('/admin/courseupdate/:id', AdminCourseController.UPDATE_COURSE)
    .put('/admin/coursegetupdate/:id', AdminCourseController.GET_UPDATE_COURSE)
    .post('/admin/teacherpost', AdminTeacherController.TEACHER_POST)
    .delete('/admin/teacherdelete/:id', AdminTeacherController.TEACHER_DELETE)
    .put('/admin/teacherupdate/:id', AdminTeacherController.UPDATE_TEACHER)
    .put('/admin/teachergetupdate/:id', AdminTeacherController.GET_UPDATE_TEACHER)
    .post('/admin/grouppost', AdminGroupController.GROUP_POST)
    .delete('/admin/groupdelete/:id', AdminGroupController.GROUP_DELETE)
    .put('/admin/groupgetupdate/:id', AdminGroupController.GET_UPDATE_GROUP)
    .put('/admin/groupupdate/:id', AdminGroupController.UPDATE_GROUP)
    .post('/admin/studentpost', AdminStudentController.STUDENT_POST)
    .delete('/admin/studentdelete/:id', AdminStudentController.STUDENT_DELETE)
    .put('/admin/studentgetupdate/:id', AdminStudentController.GET_UPDATE_STUDENT)
    .put('/admin/studentupdate/:id', AdminStudentController.UPDATE_STUDENT)
    .put('/teacher/addhomework', TeacherAddHomeworkController.ADD_HOMEWORK)
    .post('/student/uploadhomework/:id', StudentUploadHomeworkController.UPLOAD_HOMEWORK)

module.exports = router